name: Check signed commits in PR

on: pull_request_target

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: Check signed commits in PR
    runs-on: ubuntu-latest
    steps:
      - name: Check signed commits in PR
        uses: 1Password/check-signed-commits-action@v1
